name: brijesh_patel
description: Brijesh Patel - Blinkit Money Wallet Feature
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.5
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/appImages/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Light.ttf
          weight: 300
        - asset: assets/font/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700
